language: r
pandoc_version: 1.19.2.1
sudo: required
# cache:
#   packages: true
#   directories:
#   - manuscript/cache
 
cache: packages
addons:
  apt:
    packages:
      - libgit2-dev

apt_pacakges:
  - r-cran-java
  - libgsl-dev
  - libproj-dev
  - libgdal-dev
  - open-cobol

before_install:
  - sudo $(which R) CMD javareconf
  - Rscript -e 'if (!requireNamespace("BiocManager", quietly = TRUE)) { install.packages("BiocManager"); BiocManager::install("Biobase")}'


before_script:
- chmod +x ./_build_and_deploy.sh
- git config --global user.email "christoph.molnar@gmail.com"
- git config --global user.name "Christoph Molnar"
script: ./_build_and_deploy.sh
env:
  global:
  - secure: NmncQycZyb6NfYhnCuEXQip7ATuY3koIvv1XcyBpAsWuiKZIefRpXFgnR2wv9jKG/CKW8x42DMY3oPaMSzpDf60OBJp6EirRuLwAOTepmsfLzkuWNdgIQJzbEQl4hS5F0W8JglWBH+nbI6lF+ijCWSDX1yn+jlrAomHwQHT4r6y2QSxUeQRhPW2gGWSyhYM22+A1DZ8e+sTZcCLiYv+5h6j8WURJYB+6FUT/xhfOyssJR55WVsK339Q/TDNmMkn1sWhAzymd0S7Iyo1wRV+5T6SUIXcQYFFtnNrStDyvIjp1geA8sDs4pj+9+sIcd0B5EKl74G+1kSiWnCSraommKdWvTG8W8d7PhUOpCejPcsI56Jcr2rycmOQMHh4cpM++7CXDbNBN4L9MvrGq48zbg5Jt7LVf/c7l5BLCe/LWXnwYDWOg7ieGlPnKTvh10GDN4LsckwjLkwV+FcO7pprBYMybWiSE1O7rmrKInwvHG8UfjuzgLFQhsjrm2hf7ksZ0KLL8PAPrfdnF9ztUfxWvEDgGnO1lukFv15jBxkllcXa8Jxm5M+RPL+FGLsusUHOWPli0z9Pn7uvJNZ5r3xgyygngYwkca9jUpGJArU2sBg3Go/JmEw70kUGU0foPO8XfzVEYtUjCqhR4pe/Cl7kjvszIGESeZQvtcDMOwvFuTH4=




